Exercise.create(name: "Bench Press", category: "Push")
Exercise.create(name: "Incline Bench Press", category: "Push")
Exercise.create(name: "Overhead Press", category: "Push")
Exercise.create(name: "Military Press", category: "Push")
Exercise.create(name: "Dips", category: "Push")
Exercise.create(name: "Flys", category: "Push")
Exercise.create(name: "Skull Crushers", category: "Push")
Exercise.create(name: "Lateral Raises", category: "Push")

Exercise.create(name: "Pull Ups", category: "Pull")
Exercise.create(name: "Rows", category: "Pull")
Exercise.create(name: "Face Pulls", category: "Pull")
Exercise.create(name: "Hammer Curls", category: "Pull")
Exercise.create(name: "Bicep Curls", category: "Pull")

Exercise.create(name: "Sit Ups", category: "Core")
Exercise.create(name: "Planks", category: "Core")
Exercise.create(name: "Side Planks", category: "Core")
Exercise.create(name: "Hanging Leg Raises", category: "Core")

Exercise.create(name: "Squats", category: "Legs")
Exercise.create(name: "Romanian Deadlifts", category: "Legs")
Exercise.create(name: "Split Squats", category: "Legs")
Exercise.create(name: "Leg Press", category: "Legs")
